title: "Trendy Fonts "
description: "This is a blog about typography I find interesting in popular
  culture (movies/TV shows, fashion, books etc.) "
header_text: ""
footer_text: "Copyright 2020 Ugne Matuliauskaite "
header_feature_image: ../uploads/website-headliner.png
bannerheight: 20vmax
logo: ../uploads/skjermbilde-2020-09-29-kl.-18.55.52.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items: []
