title: "Trendy Fonts "
description: "This is a blog about typography I find interesting in popular
  culture (movies/TV shows, fashion, books etc.) "
header_text: ""
footer_text: "Copyright 2020 Ugne Matuliauskaite "
header_feature_image: ../uploads/design-uten-navn.jpg
bannerheight: 20vmax
logo: ../uploads/tf.png
favicon: ../uploads/tf.png
gridlayout: false
fixednavbar: true
upzoom: true
items: []
