title: "Trendy Fonts "
description: "This is a blog about typography I find interesting in popular
  culture (movies/TV shows, fashion, books etc.) "
header_text: ""
footer_text: "Copyright 2020 Ugne Matuliauskaite "
header_feature_image: ../uploads/120194786_334730340949093_5035755335983459007_n.jpg
bannerheight: 20vmax
logo: ../uploads/tf.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items: []
